remote_theme: pages-themes/minimal@v0.2.0
show_downloads: false 
title: 'Rock On'
description: 'Ergonomic ortholinear unibody keyboard by Fingerpunch'
logo: fp-logo.jpg
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have oneremote_theme: pages-themes/minimal@v0.2.0S